name: soinscosmetiques
description: Application Beauté Shop

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/blush.jpg
    - assets/images/maquillge_2.jpg
    - assets/images/palette_1.jpg
    - assets/images/mascara.jpg
    - assets/images/palette_4.jpg
    - assets/images/rouge_m1.jpg
    - assets/images/logo.jpg
    - assets/images/ground.jpg
    - assets/images/ground1.jpg